### ISSUE TITLE
HALF_ENABLE_CPP11_USER_LITERALS issues with GCC 4.8.4

### ISSUE THREAD

**Issue by alistairlow** [ARM-software/ComputeLibrary#328]
I'm trying to build with GCC 4.8.4 (which I believe is not supported, but tried anyway) using the following command:

`scons -j8 Werror=0 debug=0 neon=1 opencl=1 os=linux arch=armv7a build=native cppthreads=1 embed_kernels=1`

 I get the following errors:

<pre>include/half/half.hpp:275:8: error: missing space between â""â and suffix identifier
   half operator""_h(long double);
        ^
include/half/half.hpp:309:21: warning: base class âstruct half_float::detail::bool_type<true>â has a non-virtual destructor [-Weffc++]
   template<> struct is_float<float> : true_type {};
                     ^
include/half/half.hpp:310:21: warning: base class âstruct half_float::detail::bool_type<true>â has a non-virtual destructor [-Weffc++]
   template<> struct is_float<double> : true_type {};
                     ^
include/half/half.hpp:311:21: warning: base class âstruct half_float::detail::bool_type<true>â has a non-virtual destructor [-Weffc++]
   template<> struct is_float<long double> : true_type {};
                     ^
include/half/half.hpp:1086:24: error: missing space between â""â and suffix identifier
   friend half literal::operator""_h(long double);
                        ^
include/half/half.hpp:1199:15: error: missing space between â""â and suffix identifier
   inline half operator""_h(long double value) { return half(detail::binary, detail::float2half<half::round_style>(value)); }</pre>

I believe that the following condition in include/half/half.hpp should be changed to check against GCC 4.9 instead of 4.7.

<pre>#if HALF_GNUC_VERSION >= 407 && !defined(HALF_ENABLE_CPP11_USER_LITERALS)
    #define HALF_ENABLE_CPP11_USER_LITERALS 1
#endif</pre>

I can work around the issue by defining HALF_ENABLE_CPP11_USER_LITERALS to 0, but thought this was worth reporting anyway.

**Comment by AnthonyARM** [comment]
half is a 3rd party library, so I guess the issue should be reported here: http://half.sourceforge.net/

**Comment by alistairlow** [comment]
Ah, thanks! At least this issue will be here for anyone else that experiences the same issue.

I can also report that the core of ACL built successfully with GCC 4.8.4.
