### ISSUE TITLE
  About undefined errors, when I use the Compute Library

### ISSUE THREAD

**Issue by zt383154** [ARM-software/ComputeLibrary#257]
I compiled my program using version 17.10, and then produced the following undefined error when connecting to the static library. How do I fix it?
```
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(INESimpleFunction.o):src/runtime/NEON/INESimpleFunction.cpp:function arm_compute::INESimpleFunction::INESimpleFunction(): error: undefined reference to 'arm_compute::NEFillBorderKernel::NEFillBorderKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEActivationLayer.o):src/runtime/NEON/functions/NEActivationLayer.cpp:function arm_compute::NEActivationLayer::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::ActivationLayerInfo): error: undefined reference to 'arm_compute::NEActivationLayerKernel::NEActivationLayerKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEActivationLayer.o):src/runtime/NEON/functions/NEActivationLayer.cpp:function arm_compute::NEActivationLayer::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::ActivationLayerInfo): error: undefined reference to 'arm_compute::NEActivationLayerKernel::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::ActivationLayerInfo)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayerReshapeWeights::NEConvolutionLayerReshapeWeights(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEWeightsReshapeKernel::NEWeightsReshapeKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayerReshapeWeights::NEConvolutionLayerReshapeWeights(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::ICPPSimpleKernel::ICPPSimpleKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayerReshapeWeights::NEConvolutionLayerReshapeWeights(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'vtable for arm_compute::NEGEMMTranspose1xWKernel'
D:/EPT-Tools/EPT-Dev/android/android-ndk-r14b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayerReshapeWeights::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, bool): error: undefined reference to 'arm_compute::NEWeightsReshapeKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayerReshapeWeights::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, bool): error: undefined reference to 'arm_compute::NEGEMMTranspose1xWKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayerReshapeWeights::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, bool): error: undefined reference to 'arm_compute::NEWeightsReshapeKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::NEConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEIm2ColKernel::NEIm2ColKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::NEConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEGEMMInterleave4x4Kernel::NEGEMMInterleave4x4Kernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::NEConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEGEMMMatrixMultiplyKernel::NEGEMMMatrixMultiplyKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::NEConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NECol2ImKernel::NECol2ImKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&): error: undefined reference to 'arm_compute::scaled_dimensions(unsigned int, unsigned int, unsigned int, unsigned int, arm_compute::PadStrideInfo const&)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&): error: undefined reference to 'arm_compute::NEIm2ColKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::Size2D const&, arm_compute::PadStrideInfo const&, bool)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&): error: undefined reference to 'arm_compute::NEGEMMMatrixMultiplyKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, float)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&): error: undefined reference to 'arm_compute::NECol2ImKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*, std::pair<unsigned int, unsigned int>)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&): error: undefined reference to 'arm_compute::NEGEMMInterleave4x4Kernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&): error: undefined reference to 'arm_compute::NEGEMMMatrixMultiplyKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, float)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEConvolutionLayer.o):src/runtime/NEON/functions/NEConvolutionLayer.cpp:function arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&): error: undefined reference to 'vtable for arm_compute::NEGEMMAArch32Kernel'
D:/EPT-Tools/EPT-Dev/android/android-ndk-r14b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::NEDirectConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEDirectConvolutionLayerBiasAccumulateKernel::NEDirectConvolutionLayerBiasAccumulateKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::NEDirectConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEDirectConvolutionLayerKernel::NEDirectConvolutionLayerKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::NEDirectConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEFillBorderKernel::NEFillBorderKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&): error: undefined reference to 'arm_compute::NEDirectConvolutionLayerKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&): error: undefined reference to 'arm_compute::NEDirectConvolutionLayerBiasAccumulateKernel::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&): error: undefined reference to 'arm_compute::NEDirectConvolutionLayerKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&): error: undefined reference to 'arm_compute::NEDirectConvolutionLayerBiasAccumulateKernel::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&): error: undefined reference to 'arm_compute::NEDirectConvolutionLayerKernel::border_size() const'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEDirectConvolutionLayer.o):src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp:function arm_compute::NEDirectConvolutionLayer::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&): error: undefined reference to 'arm_compute::NEFillBorderKernel::configure(arm_compute::ITensor*, arm_compute::BorderSize, arm_compute::BorderMode, arm_compute::PixelValue const&)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayerReshapeWeights::NEFullyConnectedLayerReshapeWeights(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NETransposeKernel::NETransposeKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayerReshapeWeights::NEFullyConnectedLayerReshapeWeights(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::ICPPSimpleKernel::ICPPSimpleKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayerReshapeWeights::NEFullyConnectedLayerReshapeWeights(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'vtable for arm_compute::NEGEMMTranspose1xWKernel'
D:/EPT-Tools/EPT-Dev/android/android-ndk-r14b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.exe: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayerReshapeWeights::configure(arm_compute::ITensor const*, arm_compute::ITensor*, bool, bool): error: undefined reference to 'arm_compute::NETransposeKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayerReshapeWeights::configure(arm_compute::ITensor const*, arm_compute::ITensor*, bool, bool): error: undefined reference to 'arm_compute::NEGEMMTranspose1xWKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayerReshapeWeights::configure(arm_compute::ITensor const*, arm_compute::ITensor*, bool, bool): error: undefined reference to 'arm_compute::NEGEMMTranspose1xWKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayerReshapeWeights::configure(arm_compute::ITensor const*, arm_compute::ITensor*, bool, bool): error: undefined reference to 'arm_compute::NETransposeKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayer::NEFullyConnectedLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEIm2ColKernel::NEIm2ColKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayer::NEFullyConnectedLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEGEMMInterleave4x4Kernel::NEGEMMInterleave4x4Kernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayer::NEFullyConnectedLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEGEMMMatrixMultiplyKernel::NEGEMMMatrixMultiplyKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayer::NEFullyConnectedLayer(std::shared_ptr<arm_compute::IMemoryManager>): error: undefined reference to 'arm_compute::NEGEMMMatrixAccumulateBiasesKernel::NEGEMMMatrixAccumulateBiasesKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, bool, bool): error: undefined reference to 'arm_compute::NEIm2ColKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::Size2D const&, arm_compute::PadStrideInfo const&, bool)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, bool, bool): error: undefined reference to 'arm_compute::NEGEMMInterleave4x4Kernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, bool, bool): error: undefined reference to 'arm_compute::NEGEMMMatrixMultiplyKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, float)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEFullyConnectedLayer.o):src/runtime/NEON/functions/NEFullyConnectedLayer.cpp:function arm_compute::NEFullyConnectedLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, bool, bool): error: undefined reference to 'arm_compute::NEGEMMMatrixAccumulateBiasesKernel::configure(arm_compute::ITensor*, arm_compute::ITensor const*)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEPoolingLayer.o):src/runtime/NEON/functions/NEPoolingLayer.cpp:function arm_compute::NEPoolingLayer::NEPoolingLayer(): error: undefined reference to 'arm_compute::NEPoolingLayerKernel::NEPoolingLayerKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEPoolingLayer.o):src/runtime/NEON/functions/NEPoolingLayer.cpp:function arm_compute::NEPoolingLayer::NEPoolingLayer(): error: undefined reference to 'arm_compute::NEFillBorderKernel::NEFillBorderKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEPoolingLayer.o):src/runtime/NEON/functions/NEPoolingLayer.cpp:function arm_compute::NEPoolingLayer::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::PoolingLayerInfo const&): error: undefined reference to 'arm_compute::NEPoolingLayerKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PoolingLayerInfo const&)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEPoolingLayer.o):src/runtime/NEON/functions/NEPoolingLayer.cpp:function arm_compute::NEPoolingLayer::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::PoolingLayerInfo const&): error: undefined reference to 'arm_compute::NEPoolingLayerKernel::border_size() const'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEPoolingLayer.o):src/runtime/NEON/functions/NEPoolingLayer.cpp:function arm_compute::NEPoolingLayer::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::PoolingLayerInfo const&): error: undefined reference to 'arm_compute::NEFillBorderKernel::configure(arm_compute::ITensor*, arm_compute::BorderSize, arm_compute::BorderMode, arm_compute::PixelValue const&)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEScale.o):src/runtime/NEON/functions/NEScale.cpp:function arm_compute::NEScale::NEScale(): error: undefined reference to 'arm_compute::NEScaleKernel::NEScaleKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEScale.o):src/runtime/NEON/functions/NEScale.cpp:function arm_compute::NEScale::NEScale(): error: undefined reference to 'arm_compute::NEFillBorderKernel::NEFillBorderKernel()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEScale.o):src/runtime/NEON/functions/NEScale.cpp:function arm_compute::NEScale::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::InterpolationPolicy, arm_compute::BorderMode, arm_compute::PixelValue): error: undefined reference to 'arm_compute::NEScaleKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::InterpolationPolicy, bool)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEScale.o):src/runtime/NEON/functions/NEScale.cpp:function arm_compute::NEScale::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::InterpolationPolicy, arm_compute::BorderMode, arm_compute::PixelValue): error: undefined reference to 'arm_compute::NEScaleKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::InterpolationPolicy, bool)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEScale.o):src/runtime/NEON/functions/NEScale.cpp:function arm_compute::NEScale::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::InterpolationPolicy, arm_compute::BorderMode, arm_compute::PixelValue): error: undefined reference to 'arm_compute::NEScaleKernel::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::InterpolationPolicy, bool)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEScale.o):src/runtime/NEON/functions/NEScale.cpp:function arm_compute::NEScale::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::InterpolationPolicy, arm_compute::BorderMode, arm_compute::PixelValue): error: undefined reference to 'arm_compute::NEScaleKernel::border_size() const'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(NEScale.o):src/runtime/NEON/functions/NEScale.cpp:function arm_compute::NEScale::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::InterpolationPolicy, arm_compute::BorderMode, arm_compute::PixelValue): error: undefined reference to 'arm_compute::NEFillBorderKernel::configure(arm_compute::ITensor*, arm_compute::BorderSize, arm_compute::BorderMode, arm_compute::PixelValue const&)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(SubTensor.o):src/runtime/SubTensor.cpp:function arm_compute::SubTensor::SubTensor(arm_compute::ITensor*, arm_compute::TensorShape const&, arm_compute::Coordinates const&): error: undefined reference to 'arm_compute::SubTensorInfo::SubTensorInfo()'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(SubTensor.o):src/runtime/SubTensor.cpp:function arm_compute::SubTensor::SubTensor(arm_compute::ITensor*, arm_compute::TensorShape const&, arm_compute::Coordinates const&): error: undefined reference to 'arm_compute::SubTensorInfo::SubTensorInfo(arm_compute::ITensorInfo*, arm_compute::TensorShape const&, arm_compute::Coordinates const&)'
D:/ComputeLibrary-master17.10/build_release/libarm_compute-static.a(IScheduler.o):src/runtime/IScheduler.cpp:function arm_compute::IScheduler::IScheduler(): error: undefined reference to 'sched_getcpu'
collect2.exe: error: ld returned 1 exit status
```

**Comment by AnthonyARM** [comment]
Makre sure you link against both `arm_compute` and `arm_compute_core`

**Comment by zt383154** [comment]
Yes, Iink against both arm_compute and arm_compute_core. I use the static link library. And I found that the libarm_compute-static.a library size is only 795K, but I built it is successful. In version 17.06, it's size is 2.74M.

**Comment by AnthonyARM** [comment]
That's because in previous versions there was a bug in the build system: all the symbols of `arm_compute_core` were also included in `arm_compute`
Make sure to link against `arm_compute` first, then `arm_compute_core`

**Comment by zesiha** [comment]
Although questioner successfully built, I still have this problem. I tried to build in both ubuntu 16.04 and 17.10. Used NDK version is r14b and target architecture is 32-bit android system. I am waiting for the help of kind someone.

**Comment by zesiha** [comment]
I solved. I think that currently available library version has a problem because I successfully built using order version of library. Components of both are a little different. Especially there's no 'Ischedule.cpp' in order version. Older version is downloaded in September. Success command is as follow:

scons Werror=1 -j8 debug=1 neon=0 opencl=1 os=android arch=armv7a

**Comment by AnthonyARM** [comment]
Successfully built: closing.
